[workspace]
resolver = "2"
members = [
    "llama-cpp-sys",
    "llama-cpp",
    "examples/embeddings",
    "examples/simple",
    "examples/reranker",
    "examples/mtmd",
]

[workspace.dependencies]
# core library deps
thiserror = "2.0.11"
tracing = "0.1.27"
tracing-core = "0.1"

# examples and benchmarks
hf-hub = { version = "0.4.1" }
bindgen = "0.72.0"
cc = "1.2.15"
anyhow = "1.0"
clap = "4.5.31"
encoding_rs = "0.8.35"
tracing-subscriber = { version = "0.3", features = ["json"] }

[workspace.lints.rust]
missing_docs = { level = "warn" }
missing_debug_implementations = { level = "warn" }

[workspace.lints.clippy]
pedantic = { level = "warn" }
