[package]
name = "embeddings"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
qllama = { path = "../../qllama", version = "0.1.0" }
hf-hub = { workspace = true }
clap = { workspace = true, features = ["derive"] }
anyhow = { workspace = true }
encoding_rs = { workspace = true }

[features]
cuda = ["qllama/cuda"]
metal = ["qllama/metal"]
vulkan = ["qllama/vulkan"]

[lints]
workspace = true
