[package]
name = "reranker"
version = "0.1.86"
edition = "2021"
publish = false

[dependencies]
llama-cpp = { path = "../../llama-cpp", version = "0.1.0" }
hf-hub = { workspace = true }
clap = { workspace = true, features = ["derive"] }
anyhow = { workspace = true }
encoding_rs = { workspace = true }

[features]
cuda = ["llama-cpp/cuda"]
metal = ["llama-cpp/metal"]
vulkan = ["llama-cpp/vulkan"]

[lints]
workspace = true
