[package]
name = "openai-server"
version = "0.1.133"
edition = "2021"
publish = false

[dependencies]
llama-cpp = { path = "../../llama-cpp", version = "0.1.0" }
actix-web = "4.13.0"
serde_json = "1.0"
encoding_rs = { workspace = true }
hf-hub = { workspace = true }
tracing-subscriber = { workspace = true }

[features]
cuda = ["llama-cpp/cuda"]
metal = ["llama-cpp/metal"]
vulkan = ["llama-cpp/vulkan"]

[lints]
workspace = true
