[package]
name = "mtmd"
version = "0.1.86"
edition = "2021"
publish = false

[dependencies]
qllama = { path = "../../qllama", version = "0.1.0", features = ["mtmd"] }
clap = { workspace = true, features = ["derive"] }
encoding_rs = { workspace = true }

[features]
cuda = ["qllama/cuda"]
metal = ["qllama/metal"]
vulkan = ["qllama/vulkan"]

[lints]
workspace = true

[[example]]
name = "mtmd"
path = "src/mtmd.rs"
