[package]
name = "qllama-bench"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0"
fast-text-splitter = { git = "https://gitlab.com/qimiaio/qimia-ai-dev/fast-text-splitter.git", branch = "feat/merge_level_async_sent" }
qllama = { path = "../qllama" }
serde_json = "1.0.128"
serde = { version = "1.0.208", features = ["derive"] }
tokenizers = { version = "0.21.1", features = ["http", "onig", "esaxx_fast"] }
hf-hub = "0.5.0"
candle-core = "0.10.2"
clap = { version = "4", features = ["derive"] }

[dev-dependencies]
rayon = "1.5.1"
criterion = "0.8.2"
indexmap = "2.8.0"
serial_test = "3"

[features]
default = ["metal"]
metal = ["qllama/metal"]
cuda = ["qllama/cuda"]
cuda-no-vmm = ["qllama/cuda-no-vmm"]

[[bench]]
name = "benchmarks"
harness = false
