[package]
name = "llama-cpp-rs-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.44"
fast-text-splitter = { git = "https://gitlab.com/qimiaio/qimia-ai-dev/fast-text-splitter.git", branch = "feat/merge_level"}
llama-cpp-2 = { git = "https://gitlab.com/qimiaio/qimia-ai-dev/llama-cpp-rs.git", branch = "feat/ctx_params_n_ubatch"}
#llama-cpp-2 = { version = "0.1.66"}

[dev-dependencies]
rayon = "1.5.1"
criterion = "0.5.1"

[features]
metal = ["llama-cpp-2/metal"]
cuda = ["llama-cpp-2/cuda"]

[[bench]]
name = "benchmarks"
harness = false